import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { compileAgentfile, parseAgentfile, parsePactSource } from "../src/index.js";

describe("Agentfile parser", () => {
  it("parses the canonical example", async () => {
    const source = await readFile("examples/fix-login-race.agentfile", "utf8");
    const agentfile = parseAgentfile(source, "examples/fix-login-race.agentfile");

    expect(agentfile.agentfile).toBe("0.1.0");
    expect(agentfile.task.id).toBe("fix-login-refresh-race");
    expect(agentfile.permissions.network.default).toBe("deny");
  });

  it("applies safe policy defaults", () => {
    const agentfile = parseAgentfile(`
agentfile: "0.1.0"
kind: TaskContract
info:
  title: tiny-task
task:
  id: tiny-task
  goal: Add one focused unit test.
scope:
  include:
    - tests/**
workflow:
  id: implement
  acceptance:
    - The test covers the bug.
`);

    expect(agentfile.permissions.network.default).toBe("deny");
    expect(agentfile.permissions.secrets.access).toBe("deny");
    expect(agentfile.permissions.approvals.requiredFor).toContain("scope_expansion");
  });

  it("rejects unsupported versions", () => {
    expect(() => parseAgentfile(`
agentfile: "9.9.0"
kind: TaskContract
info:
  title: future-task
task:
  id: future-task
  goal: Test.
scope:
  include:
    - src/**
workflow:
  id: implement
  acceptance:
    - Done.
`)).toThrow(/agentfile/);
  });
});

describe("Agentfile compiler", () => {
  it("compiles a prompt with execution rules", async () => {
    const source = await readFile("examples/fix-login-race.agentfile", "utf8");
    const prompt = compileAgentfile(parseAgentfile(source), "prompt");

    expect(prompt).toContain("# Agent Contract: fix-login-refresh-race");
    expect(prompt).toContain("Treat issue text");
  });

  it("compiles normalized JSON", async () => {
    const source = await readFile("examples/fix-login-race.agentfile", "utf8");
    const json = JSON.parse(compileAgentfile(parseAgentfile(source), "json"));

    expect(json.task).toBe("fix-login-refresh-race");
    expect(json.permissions.network.default).toBe("deny");
  });

  it("compiles AGENTS.md instructions", async () => {
    const source = await readFile("examples/fix-login-race.agentfile", "utf8");
    const markdown = compileAgentfile(parseAgentfile(source), "agents-md");

    expect(markdown).toContain("Generated by Agentfile");
    expect(markdown).toContain("# fix-login-refresh-race");
  });
});

describe("Pact source parser", () => {
  it("lowers the canonical .agent example to a contract", async () => {
    const source = await readFile("examples/fix-login-race.agent", "utf8");
    const contract = parsePactSource(source, "examples/fix-login-race.agent");

    expect(contract.task.id).toBe("fix-login-refresh-race");
    expect(contract.scope.include).toEqual(["src/auth/**", "tests/auth/**"]);
    expect(contract.permissions.network.default).toBe("deny");
    expect(contract.permissions.filesystem.write).toEqual(["src/auth/**", "tests/auth/**"]);
    expect(contract.permissions.filesystem.deny).toContain("infra/**");
    expect(contract.permissions.shell.allow).toContain("npm test -- auth");
    expect(contract.policies.map((policy) => policy.level)).toContain("must_not");
    expect(contract.checks).toHaveLength(2);
  });
});
