import type { Agentfile } from "../schema.js";
import { compileAgentPrompt } from "./prompt.js";

export function compileAgentsMarkdown(agentfile: Agentfile): string {
  return compileInstructionMarkdown(
    agentfile,
    "AGENTS.md",
    "Generated by Agentfile. Edit the source contract instead of this file."
  );
}

export function compileClaudeMarkdown(agentfile: Agentfile): string {
  return compileInstructionMarkdown(
    agentfile,
    "CLAUDE.md",
    "Generated by Agentfile for Claude Code project memory. Edit the source contract instead of this file."
  );
}

export function compileCopilotMarkdown(agentfile: Agentfile): string {
  return compileInstructionMarkdown(
    agentfile,
    "GitHub Copilot custom instructions",
    "Generated by Agentfile for repository-wide Copilot instructions. Edit the source contract instead of this file."
  );
}

export function compileCursorRule(agentfile: Agentfile): string {
  const prompt = normalizeInstructionPrompt(agentfile);

  return [
    "---",
    "description: Agentfile-generated project rule",
    "alwaysApply: true",
    "---",
    "",
    "<!-- Generated by Agentfile for Cursor project rules. Edit the source contract instead of this file. -->",
    "",
    prompt.trimEnd(),
    ""
  ].join("\n");
}

function compileInstructionMarkdown(
  agentfile: Agentfile,
  heading: string,
  notice: string
): string {
  const prompt = normalizeInstructionPrompt(agentfile);

  return [
    `<!-- ${notice} -->`,
    "",
    `# ${heading}`,
    "",
    prompt.trimEnd(),
    ""
  ].join("\n");
}

function normalizeInstructionPrompt(agentfile: Agentfile): string {
  return compileAgentPrompt(agentfile)
    .replace(/^# Agent Contract:/, "#")
    .replace("## Execution Rules", "## Required Behavior");
}

